FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
	software-properties-common \
	vim

RUN add-apt-repository ppa:deadsnakes/ppa -y

RUN apt-get update && apt-get install -y \
	python3.6 \
	python3-pip

RUN rm -rf /var/lib/apt/lists/*

###########################################

WORKDIR /usr/src/app

COPY requirements.txt ./
COPY .env ./

RUN pip3 install --no-cache-dir -r requirements.txt

# COPY . .

# CMD [ "python", "./your-daemon-or-script.py" ]